"""empty message

Revision ID: 03683b9bb3b2
Revises: ca15f5b026ac
Create Date: 2020-09-23 15:52:06.625787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03683b9bb3b2'
down_revision = 'ca15f5b026ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('acronym')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acronym', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
