"""empty message

Revision ID: 0b1ff1d3e1cb
Revises: 74a41d6ae223
Create Date: 2021-08-24 19:44:04.885111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1ff1d3e1cb'
down_revision = '74a41d6ae223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_review_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('current_role', sa.Integer(), nullable=False),
    sa.Column('requested_role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('role_review_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_review_list_current_role'), ['current_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_review_list_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_review_list_requested_role'), ['requested_role'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('semester')
        batch_op.drop_column('role')

    with op.batch_alter_table('role_review_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_review_list_requested_role'))
        batch_op.drop_index(batch_op.f('ix_role_review_list_date'))
        batch_op.drop_index(batch_op.f('ix_role_review_list_current_role'))

    op.drop_table('role_review_list')
    # ### end Alembic commands ###
