"""empty message

Revision ID: 1218efcccfbc
Revises: e1056d01694a
Create Date: 2020-08-27 23:07:29.793050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1218efcccfbc'
down_revision = 'e1056d01694a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('path')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gid', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_gid'), ['gid'], unique=True)
        batch_op.drop_index('ix_notes_path')
        batch_op.drop_column('path')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('ix_units_path')
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_units_path', ['path'], unique=1)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_notes_path', ['path'], unique=1)
        batch_op.drop_index(batch_op.f('ix_notes_gid'))
        batch_op.drop_column('gid')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
