"""empty message

Revision ID: 6122a3c3b873
Revises: f03902a90b6e
Create Date: 2020-09-23 23:50:30.673076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6122a3c3b873'
down_revision = 'f03902a90b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins_list', ['id'])
    op.create_unique_constraint(None, 'courses', ['id'])
    op.create_unique_constraint(None, 'notes', ['id'])
    op.create_unique_constraint(None, 'units', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'units', type_='unique')
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'admins_list', type_='unique')
    # ### end Alembic commands ###
