"""empty message

Revision ID: b70144f1eea1
Revises: 0b1ff1d3e1cb
Create Date: 2021-08-25 15:48:00.137211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70144f1eea1'
down_revision = '0b1ff1d3e1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_review_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_role_review_list_request_date'), ['request_date'], unique=False)
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_joined_date'), ['joined_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_joined_date'))
        batch_op.drop_column('joined_date')

    with op.batch_alter_table('role_review_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_role_review_list_request_date'))
        batch_op.drop_column('request_date')

    # ### end Alembic commands ###
