"""empty message

Revision ID: c907903a86bf
Revises: 881a8153440d
Create Date: 2021-10-22 12:29:15.467313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c907903a86bf'
down_revision = '881a8153440d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_link'), ['link'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_link'))
        batch_op.drop_column('link')

    # ### end Alembic commands ###
