"""empty message

Revision ID: ca15f5b026ac
Revises: a0d498760444
Create Date: 2020-09-22 19:26:04.310347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca15f5b026ac'
down_revision = 'a0d498760444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_units_code'), 'units', ['code'], unique=True)
    op.drop_index('ix_units_acronym', table_name='units')
    op.drop_column('units', 'acronym')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('acronym', sa.VARCHAR(length=10), nullable=True))
    op.create_index('ix_units_acronym', 'units', ['acronym'], unique=1)
    op.drop_index(op.f('ix_units_code'), table_name='units')
    op.drop_column('units', 'code')
    # ### end Alembic commands ###
